USE [master]
GO

/****** Object:  Database [GB]    Script Date: 17.03.2018 15:57:07 ******/
CREATE DATABASE [GB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GB] SET RECOVERY FULL 
GO

ALTER DATABASE [GB] SET  MULTI_USER 
GO

ALTER DATABASE [GB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GB] SET  READ_WRITE 
GO


